import dcScanCode from './components/dc-scan-code/index.vue';
import dcView from './components/dc-view/index.vue';
import dcDictKey from './components/dc-dict-key/index.vue';
import dcTabs from './components/dc-tabs/index.vue';
import dcDictPopup from './components/dc-select-popup/index.vue';
import dcSelectDict from './components/dc-select-dict/index.vue';
import dcNumber from './components/dc-number/index.vue';
import dcWeight from './components/dc-weight/index.vue';
import wfSelectDialog from './components/wf-select-dialog/wf-select-dialog.vue';
import wfSelectSingle from './components/wf-select-single/wf-select-single.vue';
import dcInputScan from './components/dc-input-scan/index.vue';
import dcDragButton from './components/dc-drag-button/index.vue';
import dcPagination from './components/dc-pagination/index.vue';
import dcField from './components/dc-field/index.vue';
import dcRadio from './components/dc-radio/index.vue';
import dcScanV2 from './components/dc-scan-v2/index.vue';

import Vue from 'vue';
Vue.component('dc-scan-code', dcScanCode);
Vue.component('dc-view', dcView);
Vue.component('dc-dict-key', dcDictKey);
Vue.component('dc-tabs', dcTabs);
Vue.component('dc-select-popup', dcDictPopup);
Vue.component('dc-select-dict', dcSelectDict);
Vue.component('dc-number', dcNumber);
Vue.component('dc-weight', dcWeight);
Vue.component('dc-select-dialog', wfSelectDialog);
Vue.component('dc-select-single', wfSelectSingle);
Vue.component('dc-input-scan', dcInputScan);
Vue.component('dc-drag-button', dcDragButton);
Vue.component('dc-pagination', dcPagination);
Vue.component('dc-field', dcField);
Vue.component('dc-radio', dcRadio);
Vue.component('dc-scan-v2', dcScanV2);
